name: Update Recent Languages

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - chore/recent-languages-metrics
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/recent-languages.svg
          token: ${{ secrets.PERSONAL_GH_TOKEN || github.token }}
          user: Orchardxyz
          base: ""
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_languages_recent_days: 60
          plugin_languages_recent_load: 300
          plugin_languages_recent_categories: markup, programming
